### ISSUE TITLE
gitlab+Nexus3.6 troubles me

### ISSUE THREAD

**Issue by Dennis8274** [larscheid-schmitzhermes/nexus3-github-oauth-plugin#12]
I user gitlab + Nexus3.6,I have done everything that you had listed and something happended.....I use my gitlab'account to login nexus oss,but it hit me .it prompt me that Incorrect username or password, or no permission to use the application.what i have ignore?please : ) :) :)

**Comment by tobilarscheid** [comment]
Sorry to say @Dennis8274, but this plugin only works with git**hub**, we do not support gitlab.
