### ISSUE TITLE
Invalid Team API Call

### ISSUE THREAD

**Issue by wgorman** [larscheid-schmitzhermes/nexus3-github-oauth-plugin#13]
At the moment, this plugin makes a call to the org/teams API in Github to determine which teams a github user is a member of:
https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/blob/master/src/main/java/com/larscheidschmitzhermes/nexus3/github/oauth/plugin/api/GithubApiClient.java#L153

The github API call that should be made instead is:

https://developer.github.com/v3/orgs/teams/#list-user-teams

Until this is resolved, as long as the team membership is visible to an org member (which is recommended by github) the user will be granted permissions in nexus even though they are not a member of that team.

Thanks,

Will

**Comment by tobilarscheid** [comment]
Thanks for pointing that out! I will have a fix ready by the end of the week!

**Comment by schmitzhermes** [comment]
closed, see #14
