### ISSUE TITLE
plugin stop working after Nexus update

### ISSUE THREAD

**Issue by stefandjordjevichumanity** [larscheid-schmitzhermes/nexus3-github-oauth-plugin#33]
Seems that plugin stopped working after Nexus update to latest version **3.16.0-01**
Update was crucial for fixing security issue so no downgrade is an option for our company.

What I get from Nexus Log:

`
2019-04-16 10:54:03,032+0000 INFO  [qtp840743046-2515]  *UNKNOWN com.larscheidschmitzhermes.nexus3.github.oauth.plugin.GithubOauthAuthenticatingRealm - doGetAuthenticationInfo for stefandjordjevichumanity
`

Never had any issues before this latest update.
version of plugin: **2.0.1**

**Comment by Sczuka** [comment]
Hello,

I was experiencing the same. It verified the Nexus 3.15.2 to be the last one working properly.

The githubClient from GithubOauthAuthenticatingRealm seems not to be set. 

I got a NullPointerException at:
[githubClient.authz](https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/blob/669e80e2d93816ee4b20eeb852001eb700d7cc8f/src/main/java/com/larscheidschmitzhermes/nexus3/github/oauth/plugin/GithubOauthAuthenticatingRealm.java#L101)

I did not investigate further, but the @Inject seems not to work any longer.

Kind regards,
Armin

**Comment by gchiesa** [comment]
I confirm it's now working starting from 3.16.0-01

**Comment by RyanFrench** [comment]
Confirmed to have broken after the update to 3.16.0-02

**Comment by Ancient123** [comment]
It looks like `@PostConstruct` directives aren't working. I believe they are deprecated now. Trying a few things to see if I can work around those problems...

**Comment by Ancient123** [comment]
PR is in and code/dockerfile is available in my repo if you can't wait.

https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/pull/34

**Comment by tobilarscheid** [comment]
Wow! What a great community effort. I will merge and release tomorrow night. Thanks @Ancient123! great work!

**Comment by tobilarscheid** [comment]
fixed in [2.0.2](https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/releases/tag/2.0.2)

Thanks everyone!

**Comment by stefandjordjevichumanity** [comment]
@tobilarscheid First of all thank you for fixing this issue. Second I would really appreciate if you attach beside source code a compiled version like in previous versions, we got some automation for provisioning full setup of nexus which includes plugin. Also seems that documentation, Readme and pom are referring to old 2.0.1 versions.

**Comment by tobilarscheid** [comment]
@stefandjordjevichumanity excuse my error, release is fixed now. Let me know if everything works for you.

**Comment by stefandjordjevichumanity** [comment]
@tobilarscheid Great, everything works now as expected ! Thank you.
