### ISSUE TITLE
Error Connect Timed Out

### ISSUE THREAD

**Issue by WagnerCarvalho** [larscheid-schmitzhermes/nexus3-github-oauth-plugin#49]
Hey Guys, please ... 

Could you help me ... I'm getting a timeout, follow the nexus server log ...

GithubOauthAuthenticatingRealm - doGetAuthenticationInfo for WagnerCarvalho
GithubOauthAuthenticatingRealm - Failed authentication
Connect to api.github.com:443 [api.github.com/140.82.113.6] failed: connect timed out

my file githuboauth.properties
github.api.url=https://api.github.com
github.principal.cache.ttl=PT1M
github.org=RAIADROGASIL,RD,TEST
request.timeout.connection-request=60
request.timeout.connect=60
request.timeout.socket=10

what am I doing wrong?

**Comment by schmitzhermes** [comment]
Hi, you probably ran into an GitHub issue (see https://www.githubstatus.com/incidents/5t09j5cly2sk).
The incident is resolved now, so you can try again.
